// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PasteAligned
{
    internal sealed partial class Vsix
    {
        public const string Id = "PasteAligned.7c0fc558-6381-4143-bd58-59d4f2849d42";
        public const string Name = "Paste Aligned";
        public const string Description = @"Paste Aligned.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Yevhen Cherkes";
        public const string Tags = "";
    }
}
