// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PasteAligned
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PasteAlignedGuidString = "88419a58-a1cb-4cca-ba77-92c68372bc3e";
        public static Guid PasteAlignedGuid = new Guid(PasteAlignedGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PasteAlignedMenuGroup = 0x0001;
        public const int PasteAlignedCommand = 0x0100;
    }
}